python3 dqn_TDD_tensorforce_sim_darwinian_disney.py > log_darwinian_disney.txt

#python3 dqn_TDD_tensorforce_sim_darwinian_hopf_disney.py > log_darwinian_hopf_disney.txt
#python3 dqn_TDD_tensorforce_sim_random_mobility_disney.py > log_random_mobility_disney.txt
#python3 dqn_TDD_tensorforce_sim_darwinian_hopf_original_disney.py > log_darwinian_hopf_original_disney.txt
#python3 dqn_TDD_tensorforce_sim_darwinian_greedy_disney.py > log_darwinian_greedy_disney.txt

